# Generated by Django 3.2.3 on 2021-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
    ]
