# Generated by Django 3.2.3 on 2021-07-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='names',
        ),
        migrations.AddField(
            model_name='user',
            name='last_names',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
    ]
