# Generated by Django 3.2.3 on 2021-07-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210705_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genero',
            new_name='gender',
        ),
    ]
