# Generated by Django 3.2.3 on 2021-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Descripcion')),
                ('user', models.PositiveIntegerField(blank=True, verbose_name='Creado por')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Administrar Grupos',
                'verbose_name_plural': 'Administrar Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tribe',
            field=models.ManyToManyField(blank=True, related_name='tribes', to='users.UserGroups'),
        ),
    ]
