# Generated by Django 3.2.3 on 2021-07-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210714_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribes',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Avatar Grupo'),
        ),
    ]
