# Generated by Django 3.2.3 on 2021-08-25 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tribes_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
