# Generated by Django 3.2.3 on 2021-08-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_tribes_user'),
        ('users', '0008_auto_20210822_2227'),
    ]

    operations = [
    ]
